services:
  db:
    container_name: db
    image: postgres:17
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    container_name: jwt-rt-security
    image: abrodep/jwt-rt-security:latest
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres